name: build
on:
  push:
    branches:
      - main
  pull_request:

permissions:
    id-token: write
    contents: write              # This is required for actions/checkout@v1
    security-events: write 

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'result.json'
          severity: 'CRITICAL, HIGH'

      - name: upload result
        uses: actions/upload-artifact@v2
        with:
          name: result1
          path: result.json

